@url = http://localhost:5006

GET {{url}}/weatherforecast/
Accept: application/json

###

GET {{url}}/api/persons/first
Accept: application/json

###

GET {{url}}/log
Accept: application/json

###

POST {{url}}/api/persons
Content-Type: application/json

{
    "dni": 29626101,
    "firstname": "Ramon",
    "lastname": "Gomez"
}

###

GET {{url}}/api/persons
Accept: application/json

###

GET {{url}}/api/persons/46924236
Accept: application/json

###

GET {{url}}/api/persons/count
Accept: application/json

###

DELETE {{url}}/api/persons/46924236
Accept: application/json

###
